version: "3.3"
services:
  99x-assessment-api:
    image: 99x-assessment-api
    ports:
      - "8080:8080"
    networks:
      - item-assessment
    depends_on:
      - db
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_NAME=assessment
      - DATABASE_PORT=3306

  db:
    image: mysql:5.7
    restart: always
    networks:
      - item-assessment
    environment:
      MYSQL_DATABASE: 'assessment'
      MYSQL_USER: 'root'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

networks:
  item-assessment: