version: "3.3"
services:
  mysql-assignment:
    container_name: mysql-assignment
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=assessment
      - MYSQL_USER=demon
      - MYSQL_PASSWORD=demon
    ports:
      - 3306:3306

  assessment-api:
    container_name: assessment-api
    image: assessment-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql-assignment
    environment:
      - DATABASE_HOST=mysql-assignment
      - DATABASE_USER=demon
      - DATABASE_PASSWORD=demon
      - DATABASE_NAME=assessment
      - DATABASE_PORT=3306
    build:
      context: ./
      dockerfile: Dockerfile